coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "setup.py"
  - "docs/"
  - "examples/"