#!/bin/bash
# Fix all remaining logging calls to include correlation_id
# Story #666 - AC3, AC4, AC5

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SERVER_DIR="$PROJECT_ROOT/src/code_indexer/server"

echo "Fixing all remaining logging calls to include correlation_id"
echo "============================================================"
echo ""

# All 57 files that need fixes (in order of priority)
FILES=(
    "$SERVER_DIR/repositories/activated_repo_manager.py"
    "$SERVER_DIR/sync/recovery_strategies.py"
    "$SERVER_DIR/services/scip_self_healing.py"
    "$SERVER_DIR/sync/orchestrator.py"
    "$SERVER_DIR/app.py"
    "$SERVER_DIR/query/semantic_query_manager.py"
    "$SERVER_DIR/repositories/resource_manager.py"
    "$SERVER_DIR/web/routes.py"
    "$SERVER_DIR/services/workspace_cleanup_service.py"
    "$SERVER_DIR/sync/git_analyzer.py"
    "$SERVER_DIR/sync/progress_integrator.py"
    "$SERVER_DIR/lifecycle/global_repos_lifecycle.py"
    "$SERVER_DIR/sync/reindexing_engine.py"
    "$SERVER_DIR/auth/oidc/oidc_manager.py"
    "$SERVER_DIR/services/repository_matcher.py"
    "$SERVER_DIR/cache/__init__.py"
    "$SERVER_DIR/git/git_sync_executor.py"
    "$SERVER_DIR/repositories/resource_managed_operations.py"
    "$SERVER_DIR/services/git_operations_service.py"
    "$SERVER_DIR/services/scip_resolution_queue.py"
    "$SERVER_DIR/services/auto_watch_manager.py"
    "$SERVER_DIR/validation/health_checker.py"
    "$SERVER_DIR/managers/composite_file_listing.py"
    "$SERVER_DIR/services/branch_service.py"
    "$SERVER_DIR/services/committer_resolution_service.py"
    "$SERVER_DIR/clients/github_actions_client.py"
    "$SERVER_DIR/cache/fts_index_cache.py"
    "$SERVER_DIR/cache/hnsw_index_cache.py"
    "$SERVER_DIR/auth/oidc/oidc_provider.py"
    "$SERVER_DIR/mcp/handlers.py"
    "$SERVER_DIR/services/ssh_startup_migration.py"
    "$SERVER_DIR/validation/metrics_collector.py"
    "$SERVER_DIR/auth/audit_logger.py"
    "$SERVER_DIR/services/file_content_limits_config_manager.py"
    "$SERVER_DIR/services/repository_discovery_service.py"
    "$SERVER_DIR/services/description_refresh_scheduler.py"
    "$SERVER_DIR/sync/error_handler.py"
    "$SERVER_DIR/sync/error_reporter.py"
    "$SERVER_DIR/validators/composite_repo_validator.py"
    "$SERVER_DIR/installer.py"
    "$SERVER_DIR/auth/dependencies.py"
    "$SERVER_DIR/auth/mcp_credential_manager.py"
    "$SERVER_DIR/middleware/retry_handler.py"
    "$SERVER_DIR/middleware/sanitization.py"
    "$SERVER_DIR/repositories/golden_repo_manager.py"
    "$SERVER_DIR/repositories/repository_listing_manager.py"
    "$SERVER_DIR/routers/files.py"
    "$SERVER_DIR/services/activated_repo_index_manager.py"
    "$SERVER_DIR/services/config_service.py"
    "$SERVER_DIR/services/dashboard_service.py"
    "$SERVER_DIR/services/golden_repo_branch_service.py"
    "$SERVER_DIR/services/subprocess_executor.py"
    "$SERVER_DIR/services/search_limits_config_manager.py"
    "$SERVER_DIR/services/git_state_manager.py"
    "$SERVER_DIR/sync/progress_tracker.py"
    "$SERVER_DIR/validation/auto_recovery.py"
    "$SERVER_DIR/auto_update/service.py"
)

# Run the fixer script on all files
python3 "$SCRIPT_DIR/fix_multiline_logging_calls.py" "${FILES[@]}"

echo ""
echo "All files processed successfully!"
echo ""
echo "Next steps:"
echo "1. Run: ./lint.sh"
echo "2. Run: python3 scripts/add_missing_imports.py (if needed)"
echo "3. Verify: python3 scripts/verify_correlation_coverage.py"
